### ISSUE TITLE
Update for "La Crosse Alerts Mobile"

### ISSUE THREAD

**Issue by apiology** [jed/node-lacrosse#3]
La Crosse seems to have updated their front-end, introduced a new mobile app and API, and stopped the data feed into the existing one.  The new one is available at http://lacrossealertsmobile.com/

Details: http://support.lacrossealerts.com/la-crosse-alerts-mobile.html

**Comment by jed** [comment]
i'm confused. [this page](http://support.lacrossealerts.com/articles/category/api-program-access) says:

> La Crosse Technology does not provide an API (Application Programming Interface).

should this library be updated or deprecated?
